CREATE TABLE IF NOT EXISTS mainmenu(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
url TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS cursy(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
url TEXT NOT NULL,
body TEXT NOT NULL,
price TEXT NOT NULL,
time INTEGER NOT NULL);
